# This is a basic workflow to help you get started with Actions

name: Create OpenData GH-Page

# Controls when the workflow will run
on:
  workflow_dispatch: 
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create and deploy opendata website
        # run: git clone https://github.com/whoohoo86/gh-open-data-page.git
        uses: whoohoo86/gh-open-data-page@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WEBSITE_BRANCH: "open-data-website"
