# This is a basic workflow to help you get started with Actions

name: Create OpenData GH-Page

# Controls when the workflow will run
on:
  workflow_dispatch: 
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      - name: Fetch Repo Name
        id: repo-name
        run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        
      - name: Pull OpenDataPage
        # run: git clone https://github.com/whoohoo86/gh-open-data-page.git
        uses: actions/checkout@v2
        with:
          repository: 'whoohoo86/gh-open-data-page'
        
      - name: Create datasource.json
        uses: whoohoo86/gh-open-data-page-ds-action@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CWD:  ${{ github.workspace }}

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x

      # Runs a set of commands using the runners shell
      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm run ng -- deploy --repo=https://github.com/$GITHUB_REPOSITORY.git --base-href=/${{ steps.repo-name.outputs.value }}/ --name=EckelmannF --email=EckelmannF@rki.de --branch=open-data-website
